version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chatbot-frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always